### PR TITLE
added apis

### PR DESCRIPTION
**Pull request by arunav1101**

### CODE REVIEW

**Review by hoangle4 — CHANGES_REQUESTED** [review]
userApiRoutes.js already created to fit passport-google-auth Strategy. Please revise

**Review by KofiMatthew — APPROVED** [review]
All looks good to me.

**Review by KofiMatthew — COMMENTED** [review]
I think these are good

**Review by KofiMatthew — APPROVED** [review]
good

**Review by KofiMatthew — APPROVED** [review]
good

**Review by KofiMatthew — APPROVED** [review]

**Comment by arunav1101** [comment]
@KofiMatthew : good catch, fixed the issue

**Review by hoangle4 — CHANGES_REQUESTED** [review]
Can you empty the userApiRoutes ? We are using Google OAuth to create users and I will responsible to create to api for you guys. Please revise. Thank you

**Comment by arunav1101** [comment]
@hoangle4 : The test required the user APIs to exists. I suggest you to merge this to master and then u can pull the changes and remove it on your local and create the new api's for users and then push it to master. Are you ok with that?

**Review by hoangle4 — APPROVED** [review]

**Pull request merged**
